### ISSUE TITLE
Botan 2.3.0 Release Tracking

### ISSUE THREAD

**Issue by randombit** [randombit/botan#1156]
Botan 2.2 was about a month late wrt the quarterly release cycle, my thought is to regain that tempo by releasing 2.3.0 "on time" in early October, ~ Monday Oct 2, 2017.

Planned for 2.3.0:

- [x] ARMv8 AES support (#1146) - merged #1181
- [x] ARMv8 PMULL support (#842) - merged #1182
- [x] ARIA (#1014 and #1157) - merged
- [x] Windows Phone support (#794 #795 #796) - merged #1180
- [x] Fix CFB IV carryover #1200
- [x] ARM feature detection (via runtime probing and/or iOS APIs) - #1213
- [x] 'Raw' PSS taking a hash (#1211) - #1212
- [x] Wide block OCB #1205
- [x] Support filesystem interface on plain Win32, and add MinGW cross build to must-pass in Travis. 
- [x] Sort out GCM truncated tags #1207
- [x] Switch SM2 ciphertexts to use ASN.1 format for GmSSL compatability - #1218

Would be nice to have, might still happen but probably not:

- [ ] Add CI build for Android on Travis
- [ ] Add CI build for Windows Phone on AppVeyor
- [ ] POWER8 AES (#1206)

Considered, but not making it for 2.3:

- ~~Finish my X.509 refactor (#844)~~ too late for such a potentially destabilizing change
- ~~Build time platform feature detection~~ even if I had time to do it soon, would need more time for testing/stabilization before release. Maybe in 2.4
- ~~scrypt~~ played with it, will require some changes to PBKDF interfaces

**Comment by noloader** [comment]
> ARM feature detection (via runtime probing and/or iOS APIs)

Related, see [How to determine ARMv8 features at runtime on iOS?](https://stackoverflow.com/q/45637888/608639) on Stack Overflow.

**Comment by randombit** [comment]
Released
