### ISSUE TITLE
Botan 2.4 Release Tracking

### ISSUE THREAD

**Issue by randombit** [randombit/botan#1240]
Target release date January 8, 2018
Feature freeze ~ midnight EST on Dec 23, 2017

- [x] Get #1368 merged
- [x] Fix #1326 - #1360
- [x] Build cleanups #1346
- [x] Review #1239 
- [x] Review #1267 
- [x] Review #1332
- [x] Fix #1303
- [x] Fix #1337
- [x] Do a pass on the handbook.
- [x] Tests using tlsfuzzer
- [x] Address build issues #1237 
- [x] PSK database #1302 
- [x] Add HTTP server mode to tls_server CLI (needed for tlsfuzzer) #1315 
- [x] Update roadmap
- [x] Finish #884
- [x] Fix #1010 
- [x] Write a Botan vs OpenSSL bench script

Planned, now deferred to future
- Finish #1285
- Look at #1019 
- Build-time feature detection
- POWER8 AES (#1206)
- Add interface for tweakable ciphers
- Support for EME*

**Comment by randombit** [comment]
Should look at #1010 also

**Comment by randombit** [comment]
Testing phase

- [ ] FreeBSD x86-64 build
- [ ] AIX ppc build
- [ ] Linux ppc64le build
- [ ] Linux aarch64 build
- [ ] valgrind run
- [ ] Full ASan/UBSan run
- [ ] More tlsfuzzer testing
- [ ] Run TLS-Attacker
- [ ]

**Comment by randombit** [comment]
2.4.0 tagged and released.

**Comment by lambdafu** [comment]
Congrats! :tada: :balloon:
