### ISSUE TITLE
Botan 2.5.0 release

### ISSUE THREAD

**Issue by randombit** [randombit/botan#1396]
Release date April 2, 2018, feature freeze March 23

- [ ] Improve tests of Python module
- [x] Update docs wrt #1448 #1395 #1394 
- [ ] Fix check_crl_online #951 
- [x] Fix DSA #1502
- [x] Fix #210
- [x] Support multiple DNS names in `gen_pkcs10` and `gen_self_signed`
- [x] Fix #983
- [x] Check #500
- [x] Fix random_integer test #1476
- [x] Issue burndown: all tickets either categorized or closed
- [x] Improve tests of CLI util
- [x] Fix Windows build issues (in #1456)
- [x] Fix timing_test cli (#1465)
- [x] Refactor CurveGFp and EC_Group to support shared representation
- [x] Make use of shared repr and precomputations to optimize scalar mult
- [x] AES for POWER (#1206)
- [x] Clean up x25519 code (#1391)
- [x] Finish and merge #1285, support PSS in TLS
- [x] Add ability to control/customize TLS extensions (#1186)
- [x] Add callback for client auth giving list of CAs (#1261)
- [x] Remove vestigial compression support from TLS

**Comment by randombit** [comment]
Tagged and released.
