### ISSUE TITLE
2.11.0 Release

### ISSUE THREAD

**Issue by randombit** [randombit/botan#1882]
Target date July 1, 2019

Items

- [ ] Roughtime (#1842) - not ready
- [x] Asio integration (#1839)
- [x] New XMSS (#1858)
- [x] Update XMSS format/OID (https://tools.ietf.org/html/draft-vangeest-x509-hash-sigs-03)
- [x] Linux certstore (#1885)
- [x] Improve Python situation (#1906)
- [x] Switch to xz (#1872)
- [ ] Follow up on rpath (#1505). Maybe for simplicity just remove rpath from `botan` and leave it in `botan-test`? Then production binaries are unaffected and we can remove the Darwin specific hacks during install.
- [x] Argon2 base algo
- [x] Argon2 extras: Support long outputs, PBKDF integration, password hash format, documentation
- [x] BoGo shim/tests
- [ ] Document TLS testing procedures
- [x] Document test framework
- [x] Document CI system
- [x] Document updated Python module
- [ ] Address all open documentation tickets
- [x] Update roadmap
- [ ] Document project structure

**Comment by reneme** [comment]
> Document test framework

👍

**Comment by randombit** [comment]
@reneme Yeah part of a drive to make contributing easier; you and your team just recently made a bunch of changes so if anything occurs to you that would have made things easier to get started lmk.

**Comment by randombit** [comment]
Released.

Tarball SHA-256 f7874da2aeb8c018fd77df40b2137879bf90b66f5589490c991e83fb3e8094be
