### ISSUE TITLE
Botan 3.0 pre-release checklist

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3209]
Changes still needed prior to alpha1:

- [x] #3019
- [x] #3402 
- [ ] Internal PK key refactoring for DL/EC (current WIP by Jack)
  - [x]  #3210 
  - [ ] ~EC equivalent work~
- [ ] Final TLS 1.3 pieces
  - [x] #3322
  - [x] #3316
  - [x] #3337
  - [ ] #3324
  - [x] #3321
  - [ ] (Maybe optional): Introduce `std::shared_ptr` in `Credentials_Manager::trusted_cas()` and remove deprecated `Creds_Mgr::cert_chain()`
- [x] #3328 
- [ ] ~PK RNG& lifetime issues~
- [x] #3347 
- [x] TLS 1.3 migration Guide (#3308)
- [x] Get Dilithium X.509 working (#3208, #3212)
- [x] #3227
- [x] #3225 / #3211 
- [x] Look at Kyber key encoding (#3179)
- [x] ZFEC FFI (#3190)
- [x] #3146
- [x] #3169
- [x] Remove use of raw pointers where possible (#3216 and #2677)
- [ ] Maybe more `std::span` (#3318)

After alpha1, before final release:

- [ ] Test builds of KeepassXC, SoftHSM, RNP, etc (Jack)
- [ ] Review documentation especially the migration guide (Jack)
- [x] Complete the change notes (Jack)
- [x] Run the one-off checks and static analyzers (`clang-tidy`, `test_all_configs.py`, etc)

~~Current timeline which will probably not be met :)~~

* ~~Alpha1 on Feb 13th~~
* ~~3.0 release candidate on March 6th~~
* ~~If all goes well, 3.0.0 March 13th~~

Revised schedules posted below.

**Comment by reneme** [comment]
I'd be glad to have experimental modules in 3.0 as well. Especially to use for the (upcoming) PQC implementations. https://github.com/randombit/botan/discussions/3110

**Comment by randombit** [comment]
There is still a lot of work in the queue and additionally Mailman is broken on my mail box, I'll need to upgrade/migrate to Mailman3 in order to send out any announcements. That's probably going to eat an entire day for me.

New schedule:

* Alpha1 on March 6th
* RC on March 20th
* 3.0.0 April 3rd

If things get done faster than I expect we can always release Alpha1 early and adjust as we go.

**Comment by randombit** [comment]
There has been a lot of work and some nice convergence in the last 3 weeks - more TLS improvements, the internal signature padding improvements, a lot of `clang-tidy` fixes, and testing clean with the latest Wycheproof. But ... we are not all the way there just yet.

Right now I'm leaning towards keeping the timeline as it except for skipping alpha2 altogether and going straight to the RC on March 20th and 3.0.0 in early April. If the RC doesn't seem ready in time that probably does delay 3.0.0 since we probably do want to give a couple of weeks for people to kick the tires, lest we have to immediately do a patch release fixing silly bugs. Given the recent rate of progress, and the relatively limited number of open todos I think RC on March 20th is still achievable.

**Comment by randombit** [comment]
Things are going exactly to plan, ie only slightly behind schedule.

I need to review #3409 #3411 and #3412 before the RC.

Everything else (eg EC key refactoring work) is delayed until post 3.0, and so is either cancelled or will be limited to what we can accomplish without breaking compatability.

I think best course right now is to delay everything one week from the prior schedule, ie RC is now March 27th and final release is April 10th.

Shifting the release schedule to the second Monday of the quarter is actually nicer as it avoids Jan 1, April 1, and July 4th as potential conflicts.

**Comment by randombit** [comment]
Also #3019 should get fixed

**Comment by randombit** [comment]
So close :) The final must-have for the RC is #3409 and that's basically done, modulo one question and a small merge conflict.

I want to minimize anything disruptive or risky between the RC and the final release. My plan is basically

* Documentation/examples
* CLI improvements
* New tests if they occur to me
* Introducing `std::span` where low risk
* Cleaning up ticket backlog

Also I (still) need to fix mailman. Or give up on it and create a Substack.

**Comment by reneme** [comment]
May I propose a last-second API adaption in the `Session_Manager` (#3451) before the freeze. 😄

**Comment by randombit** [comment]
I want to get #3480 merged before the final release, but otherwise we're good to go. Current plan is to spin the final release tomorrow, in the evening my time.

**Comment by randombit** [comment]
Done https://botan.randombit.net/releases/Botan-3.0.0.tar.xz
