### ISSUE TITLE
Refactor tracking issue

### ISSUE THREAD

**Issue by ksanderon** [randombit/botan#973]
I would like to improve in nearest days(weeks?) quality of botan code - this will be splited in some steps for easier review process.

**Planned content:**
* [x] Basic refactor ( #965 ):
    * [x] fixes for deprecated constructions in c++11 and later (explicit rule of 3/5 or implicit rule of 0 and other violations)
    * [x] `default` specifier instead of `{}`
    * [x] removal of unreachable code (for example `return` after `throw`)
    * [x] removal of compilation unit only visible, but not used functions
    * [x] get rid of  for `throw()` specifier in favor for `BOTAN_NOEXCEPT`
    * [x] removal of not needed semicolons
* [x] Support for cmake in configure.py ( #967  )
    * [x] mac os x
    * [x] linux x86_64
* [ ] Code reformat with astyle:
    * [x] astyle configuration file ( #967 )
    * [ ] reformated code delivery
        * [x] cli ( #980 )
        * [x] tests ( #980 )
        * [ ] lib
             * [ ] asn1
             * [ ] base
             * [ ] block
             * [ ] codec
             * [ ] entropy
             * [ ] ffi
             * [ ] filters
             * [ ] hash
             * [ ] kdf
             * [ ] mac
             * [ ] math
             * [ ] misc
             * [ ] modes
             * [ ] passhash
             * [ ] pbkdf
             * [ ] pk_pad
             * [ ] prov
             * [ ] pubkey
             * [ ] rng
             * [ ] stream
             * [ ] tls
             * [ ] utils
             * [ ] x509
* [ ] get rid of raw pointers - smart pointers instead in 99% of cases (may be some minor interface change will be needed - in case of `X * X::copy/clone() and friends` -> `std::unique_ptr<X> X::pristine()`)
    * [x] helper header file which provide missed stuff in std (+ fixes for compilers incompatibility if needed):
        * [x] `make_unique` (#974)
* [ ] RAII in some places,
* [ ] removal of not needed `virtual` and virtual inheritance, 
* [ ] lvalue ref instead or rvalue ref if rvalue not needed
* [ ] `final` for classes which should not be base for something
* [ ] refactor C++03 style private ctors/dctors style in favour of C++11 `delete`
* [ ] refactor `for` loops refactor in fovour of `for ... in`
* [ ] add install target support in cmakefile generated by config.py

Optional but possible and (maybe) reasonable in some places:
 * [ ] introduce PIMPL idiom (https://en.wikipedia.org/wiki/Opaque_pointer) - to increase public API binary compatibility.
 * [ ] remove forward declarations without incrased build time -  forward declarations may cause subtle bugs for example:
```
// first compilation unit
struct A
{
  A() { cerr << "hello!\n"; }
  ~A() { cerr << "Bye!\n"; }
};
A* create() { return new A; }

// second compilation unit
struct A;
A* create();
int main()
{
  auto* p = create();
  delete p;
}
// only "Hello" will be visible - no "Bye" :/
```

Feel free for comments, or stop me with stuff which can't be accepted.

**Comment by randombit** [comment]
Only thing we couldn't take right now is anything changing public API (eg as mentioned for smart ptr conversions). However in most cases it will probably prove easy to have a (deprecated) raw pointer interface matching the current API, plus a new smart ptr interface.

And, thanks! :)

**Comment by ksanderon** [comment]
Yes, this could be done this way:

from:
```
class A
{
public:
   A * clone()
   {
   return new A(); 
   }
};
```
to:
```
class A
{
public:
   std::unique_ptr<A> pristine() const
   { 
   return Botan::make_unique<A>(); 
   }

   BOTAN_DEPRECATED("Use pristine() instead")
   A * clone() const
   {
   return prinstine().release(); 
   }
};

```

**Comment by randombit** [comment]
Yes all that looks good. Also `pristine` is a much better name for this operation.
